server:
  port: 8080
  servlet:
    context-path: /management
spring:
  main:
    web-application-type: SERVLET
  application:
    name: management-security
  profiles:
    include: datasource
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cache:
    type: redis
    redis:
      #redis中缓存超时的时间，默认60000ms
      time-to-live: 3600000ms
      #缓存数据key是否使用前缀，默认是true
      use-key-prefix: false
      #缓存数据key的前缀，在上面的配置为true时有效，
      cache-null-values: false
logging:
  level:
    root: info
swagger:
  enabled: true