server:
  port: 8080
  servlet:
    context-path: /management
spring:
  main:
    web-application-type: SERVLET
  application:
    name: management-security
  profiles:
    include: datasource
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cache:
    type: redis
    redis:
      #redis中缓存超时的时间，默认60000ms
      time-to-live: 3600000ms
      #缓存数据key是否使用前缀，默认是true
      use-key-prefix: false
      #缓存数据key的前缀，在上面的配置为true时有效，
      cache-null-values: false
mybatis-plus:
  mapper-locations:
    - classpath:mapper/capital/*Mapper.xml
    - classpath:mapper/management/*Mapper.xml
    - classpath:mapper/user/*Mapper.xml
  type-aliases-package:
    - com.supergenius.admin.capital.model
    - com.supergenius.admin.management.model
    - com.supergenius.admin.user.model
  #  检验xml配置文件
  check-config-location: true
  #  MyBatis 的执行器
  executor-type: simple
  #  原生配置
  configuration:
    aggressive-lazy-loading: true
    #    懒加载
    lazy-loading-enabled: true
    #    自动映射策略
    auto-mapping-behavior: partial
    #    自动映射时未知列或未知属性处理策略
    auto-mapping-unknown-column-behavior: none
    cache-enabled: false
    #    指定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法
    call-setters-on-nulls: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #    列标签
    use-column-label: true
    #    允许在嵌套语句中使用分页
    safe-result-handler-enabled: true
    #    允许 JDBC 支持自动生成主键
    use-generated-keys: false
    #    允许使用方法签名中的名称作为语句参数名称
    use-actual-param-name: true
    #    允许在嵌套语句中使用分页
    safe-row-bounds-enabled: true
  global-config:
    db-config:
      #      是否开启大写命名
      capital-mode: true
      #      全局默认主键类型
      id-type: uuid
      #      表名前缀
      table-prefix: TB_
      #      表名是否使用下划线命名
      table-underline: true
      select-strategy: not_null
      update-strategy: not_null
      insert-strategy: not_null
      #      扫描枚举
  type-enums-package: com.supergenius.admin.enums
logging:
  level:
    root: info
#    com.supergenius.admin.capitaldb.mapper: debug
#    com.supergenius.admin.management.mapper: debug
#    com.supergenius.admin.user.mapper: debug
swagger:
  enabled: true